[package]
name = "the-watcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
axum = "0.7.4"
axum-auth = "0.7.0"
axum-test = "14.2.2"
axum_session = "0.12.1"
cached = "0.47.0"
chrono = "0.4.31"
config = "0.13.4"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.11"
dashmap = "5.5.3"
deadpool = "0.10.0"
envy = "0.4.2"
futures = "0.3.30"
itertools = "0.12.0"
num = "0.4.1"
predicates = "3.0.4"
rangemap = "1.4.0"
rayon = "1.8.0"
readable = "0.16.0"
redis = "0.24.0"
regex = "1.10.2"
scraper = "0.18.1"
sea-orm = "0.12.10"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
sqlx = { version = "0.7.3", features = ["runtime-tokio", "tls-native-tls", "postgres", "macros", "uuid", "chrono", "json"] }
threadpool = "1.8.1"
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.40"
tracing-serde = "0.1.3"
tracing-subscriber = { version = "0.3.18", features = ["json"] }
uuid = "1.6.1"
want = "0.3.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
